spring:
  application:
    name: onboarding

  datasource:
    url: jdbc:h2:tcp://localhost/~/onboarding
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

  token:
    expiration:
      # 60분
      access: 3600000
      # 7일
      refresh: 604800000